In [7]:
import numpy as np
x = np.array([[1],[1]])
print(x)
A = np.array([[1,3],[2,1]])
print(A)

[[1]
 [1]]
[[1 3]
 [2 1]]


In [8]:
print(x@x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [9]:
print(x.T @ np.linalg.inv(A) @ x)

[[0.6]]


In [10]:
print(x @ x.T)

[[1 1]
 [1 1]]


In [11]:
print(x.T @ A @ x)

[[7]]


In [12]:
print(x.T @ x)

[[2]]
