**Please write a generic python function (in a separate package) which implements a generic version of the K-means algorithm. Your function should take as input a $d$-dimensional data set and the number of clusters into which you wish to group your data set. Return the means of your K-clusters and the assigned labels of your dataset (use 1-of-K coding to represent your labels). Initialize your means with two random samples.**

In [14]:
import numpy as np
from importer import *

X= np.array ([[3,5,8,16,22,31,36,43,50,59,67,73,84,96,103,111,126,141,145,160]])
d = X.shape[0]
N = X.shape[1]
C = [0,1,2]
K = len(C)
u = [13, 39, 69]

for i in range(10):
    Xk = np.zeros((N,K))
    for k in range(K):
        Xk[:,k] = np.linalg.norm((X - u[k]), axis=0)
    l = np.argmin(Xk, axis=1)
    print(l)
    u = []
    for c in C:
        u.append((np.sum(X[:,l==c], axis=1) / np.sum([l==1]))[:,np.newaxis])
    print(u)
    print(i)


[0 0 0 0 0 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2]
[array([[13.5]]), array([[40.]]), array([[291.25]])]
0
[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[array([[3.6]]), array([[88.33333333]]), array([[0.]])]
1
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
[array([[13.66666667]]), array([[101.25]]), array([[0.]])]
2
[2 2 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
[array([[18.72727273]]), array([[105.90909091]]), array([[0.72727273]])]
3
[2 2 2 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[array([[25.7]]), array([[110.6]]), array([[1.6]])]
4
[2 2 2 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
[array([[36.]]), array([[115.44444444]]), array([[1.77777778]])]
5
[2 2 2 2 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[array([[47.625]]), array([[120.75]]), array([[4.]])]
6
[2 2 2 2 2 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
[array([[63.28571429]]), array([[126.]]), array([[7.71428571]])]
7
[2 2 2 2 2 2 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
[array([[58.85714286]]), array([[126.]]), array([[12.14285714]])]
8
[2 2 2 2 2 2 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
[array([[58.8571428